class Car:
    def __init__(self, mass, radius_wheel, engine):
        '''The function initializes the attributes of an object and calls the reset method.
        
        Parameters
        ----------
        mass
            The mass parameter represents the mass of the object or vehicle. It is a measure of the amount of
        matter in the object and is measured in kilograms (kg).
        radius_wheel
            The radius of the wheel of the object. It is used to calculate the distance traveled by the object
        when the wheel rotates.
        engine
            The engine parameter refer to the engine used by the car.
        '''
        self.mass = mass
        self.radius_wheel = radius_wheel
        self.engine = engine
        self.reset()

    def reset(self):
        '''The `reset` function sets the speed to 0 and calls the `reset` method of the `engine` object.
        
        '''
        self.speed = 0
        self.engine.reset()

    def accelerate(self, delta_t):
        '''The function calculates the acceleration of a vehicle and updates its speed based on the force
        generated by the engine.
        
        Parameters
        ----------
        delta_t
            The parameter `delta_t` represents the change in time. It is used to calculate the change in
        speed over a given time interval.
        
        '''
        force_engine = self.engine.force_wheel(self.radius_wheel)
        acceleration = force_engine / self.mass
        self.speed += acceleration * delta_t
        self.engine.update_rpm(self.radius_wheel, self.speed)
    
    def force_wheel(self):
        return self.engine.force_wheel(self.radius_wheel)